export default {
	"mcc": {
		"name": "Patrimoine québécois",
		"url": "http://mcc.witify.io",
		"category": "webapp",
		"client": "Ministère de la Culture et des Communications",
		"dev_time": "1",
		"deliverables": [
			"webapp",
			"ux",
		],
		"technologies": [
			"vue",
			"nodejs",
			"webpack",
			"sass",
			"html-5",
			"css-3",
			"git",
			"digitalocean",
			"nginx",
		],
		"gallery": {
			"1": "1.jpg",
			"2": "2.jpg",
			"3": "3.jpg",
			"4": "4.jpg",
		}
	},
	"save": {
		"name": "SAUVéR",
		"url": "http://sauver-system.com",
		"category": "webapp",
		"client": "BrioConcept Inc",
		"dev_time": "4",
		"deliverables": [
			"webapp",
			"ux",
			"api",
		],
		"technologies": [
			"laravel",
			"vue",
			"redis",
			"nodejs",
			"webpack",
			"jquery",
			"sass",
			"html-5",
			"css-3",
			"git",
			"digitalocean",
			"nginx",
		],
		"gallery": {
			"1": "1.jpg",
			"2": "2.jpg",
			"3": "3.jpg",
			"4": "4.jpg",
			"5": "5.jpg",
			"6": "6.jpg",
			"7": "7.jpg",
			"8": "8.jpg",
			"9": "9.jpg",
		}
	},
	"jussaume": {
		"name": "Mobilier Jussaume",
		"url": "http://jussaume.ca",
		"category": "website",
		"client": "Jussaume Entreprise Inc",
		"dev_time": "1",
		"deliverables": [
			"website",
			"branding",
			"render",
		],
		"technologies": [
			"vue",
			"nodejs",
			"webpack",
			"sass",
			"html-5",
			"css-3",
			"jquery",
			"javascript",
			"git",
			"digitalocean",
			"nginx",
		],
		"gallery": {
			"0": "home.png",
			"1": "page_1.png",
			"2": "page_2.png",
			"3": "page_3.png",
			"4": "contact.png",
		}
	},
	"coupsur": {
		"name": "Coup Sur",
		"url": "http://adapass.com",
		"category": "webapp",
		"client": "Baseballtown Inc",
		"dev_time": "7",
		"deliverables": [
			"webapp",
			"embedded-system",
			"api",
		],
		"technologies": [
			"laravel",
			"arduino",
			"vue",
			"c++",
			"nodejs",
			"socket.io",
			"redis",
			"webpack",
			"sass",
			"html-5",
			"css-3",
			"javascript",
			"git",
			"digitalocean",
			"nginx",
		],
		"gallery": {
			"1": "page_1.png",
			"2": "page_7.png",
			"3": "page_4.png",
			"4": "page_3.png",
			"5": "page_6.png",
			"6": "page_2.png",
			"7": "page_5.png",
		}
	},
	"occ": {
		"name": "Online Crash Courses",
		"url": "https://onlinecrashcourses.com",
		"category": "webapp",
		"client": "Online Crash Courses",
		"dev_time": "4",
		"deliverables": [
			"webapp",
			"branding",
			"ux",
		],
		"technologies": [
			"laravel",
			"vue",
			"nodejs",
			"stripe",
			"jquery",
			"auth0",
			"webpack",
			"sass",
			"html-5",
			"css-3",
			"git",
			"digitalocean",
			"nginx",
		],
		"gallery": {
			"1": "page_1.png",
			"2": "page_2.png",
			"3": "page_3.png",
			"4": "page_4.png",
			"5": "page_5.png",
			"6": "iphone_1.png",
			"7": "iphone_2.png",
			"8": "iphone_3.png",
		}
	},
	"elium": {
		"name": "Elium",
		"url": "http://elium.ca",
		"category": "webapp",
		"client": "Elium Inc",
		"dev_time": "3",
		"deliverables": [
			"webapp",
			"branding",
		],
		"technologies": [
			"laravel",
			"vue",
			"nodejs",
			"webpack",
			"sass",
			"html-5",
			"css-3",
			"git",
			"digitalocean",
			"nginx"
		],
		"gallery": {
			"1": "branding.png",
			"0": "page_2.png",
			"2": "page_1.png",
			"video": {
				"url": "https://player.vimeo.com/video/184901788",
				"poster": "poster.png"
			}
		}
	}
}